### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Cu3PO42** [robocode-dev/robocode-api-bridge#2]
Hello again!

While packaging this library with Nix, I realized there is no license specified for this code. Did you intend to also license this under the Apache Source License Version 2? It would be great if you could clarify.

Thanks in advance!

**Comment by flemming-n-larsen** [comment]
@Cu3PO42 
You are right. The Robocode API Bridge for Tank Royale is also licensed Apache Source License Version 2. 😊
I will make sure to add the license to the sources.

**Comment by Cu3PO42** [comment]
Thank you so much!
